### ISSUE TITLE
bug: PrincipalDetails username 설계 미스

### ISSUE THREAD

**Issue by wonslee** [ShyPolarBear/Server#45]
## 📌  Issue

Security 전역에서 쓰는 PrincipalDetails의 getUsername이 providerId를 리턴하고 있어요!
-> userRepository.findByProviderId() 에서 유니크한 결과가 아니라 2개 이상이 나오게 됩니다. 
인증이 필요한 모든 API에서 필터를 거칠 때 에러가 발생하네요

![image](https://github.com/ShyPolarBear/Server/assets/72124326/10d1c7a3-3a95-4e68-a404-b88d60a28dd9)

![Screenshot from 2023-08-10 19-50-06](https://github.com/ShyPolarBear/Server/assets/72124326/6fd8e15c-d82e-4c04-abb8-5bc863774823)

![image](https://github.com/ShyPolarBear/Server/assets/72124326/d8429a88-911b-4d89-9c39-eae78201d9a1)

댓글 수정, 삭제 API 테스트해면서 DB에 유저를 하나 더 넣었더니 발생했어요

제 생각엔 유니크한걸로 username을 바꾸는게 좋을듯합니다!
제가 Security를 직접 구현해본적은 없어서 좋은 아이디어 있으시면 알려주십쇼

## 📝  To-do

- [ ] 대체할 필드 정하기
- [ ] 고치기

**Comment by 0sunset0** [comment]
provider id는 유니크해요!!
유니크 제약조건으로 바꾸면 될 거 같아요
DB에 저렇게 들어간 이유는 제가 제약조건을 꼼곰히 명시하지 않고 더미 데이터를 넣어놨기 때문입니다

**Comment by wonslee** [comment]
아 그런가요?? 제가 몰랐네요 이슈 닫을께요

**Comment by 0sunset0** [comment]
복쟉복쟉 플럽에서도 소셜이메일을 userName으로 쓰고 있는데, 
여기서 소셜이메일은 chi6465@gmail.com 이런 메일이 아니라
{providerid} + "@KAKAO" 이런 식으로 만들어서 넣어주고 있어요. 
저는 "@KAKAO" <- 이걸 안넣은겁니다!!
