### ISSUE TITLE
엔티티 필드 제약 조건 추가 (@Column)

### ISSUE THREAD

**Issue by wonslee** [ShyPolarBear/Server#47]
## 📌  Feature Issue
현재 엔티티 필드에는 제약조건이 없는 상태

방법은 두가지

1. `@Column` 으로 DB DDL상의 제약조건을 주는 방법
2. , javax.validation.constraints의 NotNull 등을 쓰는 방법

같이 얘기해보고 결정하면 될것 같습니다!

참고 : https://hyeon9mak.github.io/not-null-vs-column-nullable-false/

## 📝  To-do

이 부분 채워주십쇼

- [x] @wonslee  : quiz, notification, point
- [x] @0sunset0  : user, ranking, prize, feed

**Comment by 0sunset0** [comment]
validation을 테이블에 다들 쓰시나요...!?
(구현 안할 수도 있지만) 휴면계정은 user 참조를 하고 있지 않아서 
저는 1번에 마음이 약간 기울여집니다 ~!

**Comment by wonslee** [comment]
아하 그러시군요
전 둘다 상관 없습니다
1번으로 가실까요?

**Comment by 0sunset0** [comment]
네 좋습니다~
@EgongD
