### ISSUE TITLE
[전체 부모 댓글 조회] join할 때 데이터 늘어남

### ISSUE THREAD

**Issue by 0sunset0** [ShyPolarBear/Server#87]
## 📌  문제

전체 부모 댓글 조회할 때, 
댓글 좋아요랑 댓글이랑 fetch join을 안해서
댓글 좋아요 개수만큼 댓글이 늘어나는 문제가 있네요!
(fetch join 안해서 db에서 limit 해오는 거 아닐까요..? ) 

예전에 공유했던 [fetch join과 limit을 같이 쓸 때 주의하자](https://bottom-to-top.tistory.com/45)
 
![image](https://github.com/ShyPolarBear/Server/assets/81086966/7849e2fb-b97a-454e-8382-2ef82c977180)

전체 댓글 조회에서 id가 1351인 댓글이 두 개 보여집니다!
![image](https://github.com/ShyPolarBear/Server/assets/81086966/6f1cb756-1a96-438e-a159-58affdf54476)

**Comment by wonslee** [comment]
너무 늦게 봤네요,, PR 올렸습니다!
