### ISSUE TITLE
Quiz - DTO 변환 메서드의 OCP 위반

### ISSUE THREAD

**Issue by wonslee** [ShyPolarBear/Server#90]
@0sunset0 한번 같이 고민해주시면 감사하겠습니다..! 노을님의 지혜를 빌려주십쇼

OOP 공부를 하다가 문득 떠올라서 적게 됐습니다.

이전에 제가 구현했던 [Quiz 엔티티 객체](https://github.com/ShyPolarBear/Server/blob/f4da1a84a4ba135db7cc25d40e16de4add18ec68/src/main/java/com/shy_polarbear/server/domain/quiz/model/Quiz.java)에 대한 서브 클래스들은 갖고 있는 필드가 조금씩 다릅니다. 

OX 퀴즈는 선택지가 없으므로 O,X 여부만 갖고 있고 객관식 퀴즈는 선택지 리스트 필드를 갖습니다.

문제는 [여기](https://github.com/ShyPolarBear/Server/blob/f4da1a84a4ba135db7cc25d40e16de4add18ec68/src/main/java/com/shy_polarbear/server/domain/quiz/service/QuizService.java)인데, Quiz 슈퍼 클래스를 받아서 각 서브 클래스별로 분기 처리, 다운 캐스팅을 해서 응답 DTO로 바꿔줍니다. 
DTO에서는 각 클래스에 따라 다르게 받고 있구요...

만약 퀴즈의 종류가 더 많아진다면 (기능 확장) 기존의 코드가 수정되기 때문에 OCP 원칙을 위반한다고 생각했습니다.

기왕 추상 클래스로 만든거 이점을 살려보고 싶은데 고민이 됩니다.

1. Quiz에서 DTO 변환 추상 메서드 만들기
이렇게 하면 각 서브 클래스에서만 구현을 해주면 되니 확장에 열려있게 되고 변경에는 닫혀있게 됩니다.
근데... 엔티티에서 DTO를 의존해선 안 된다고 배웠습니다. 음.. 트레이드 오프라고 할 수 있을까요? 

```java
    abstract protected QuizCardResponse toResponse();
```

2. VO 만들기
쓰고 보니 말장난 같네요.

```java
    abstract protected QuizVO toVO();
```

조금 더 좋은 방법이 있을까요?

**Comment by 0sunset0** [comment]
원석님 제가 생각해봤는데 if문이나 switch문 분기는 피할 방법이 생각나질 않네요..ㅎㅎ
엔티티 안에 dto를 아는 것도 dto의 변화가 엔티티에 전파 되기 때문에 그것대로 문제일 것 같고,,,

지금 코드에서 만약 새로운 기능이 추가된다면 dto에 필드도 추가 되고 메서드도 추가되니
dto도 상속 구조로 가져가고 QuizCardResponse에서 하위타입을 반환하는 방식이 생각나네요,,

ox퀴즈인지 객관식인지 구별하는 로직을 
서비스에서 다운캐스팅 하는게 아니라
QuizCardResponse에게 밀어넣는 것도 좋을 것 같긴 합니다!

이건 다른 얘기지만
엔티티에도 QuizType을 넣어서 분기처리 할 때 사용하면 깔끔해질 것 같네요
보통은 하위타입이 뭔지 알고 싶을 때가 많으니까..?

**Comment by 0sunset0** [comment]
## 정적팩토리 장점 중 하나

### 반환 타입의 하위 타입 객체를 반환할 수 있다.
이러한 방법을 사용하면 구현 클래스를 공개하지 않고 원하는 객체를 반환하게 할 수 있어 API를 작게 유지할 수 있습니다.
자바 8부터는 인터페이스에서도 정적 메서드 선언이 가능해졌으므로 인터페이스에서도 간단하게 이 방법을 구현할 수 있습니다.
```java
public interface Item {

    void print();

    static Item createItem(String name){
        return new Book(name);
    }
}

class Book implements Item
{
    String name;

    Book(String name){
        this.name = name;
    }

    @Override
    public void print() {
        System.out.println(name);
    }
}
```

https://sun-22.tistory.com/84

**Comment by 0sunset0** [comment]
써놓고 보니 ocp 애기는 거의 안했네요 ㅋㅋㅋ

**Comment by wonslee** [comment]
오오 알림이 안 와서 지금 봐버렸네요,, ㅋㅋㅋㅋㅋ친절한 답변 감사합니다 곧 PR 올리겠씁니다

> QuizCardResponse에게 밀어넣는 것도 좋을 것 같긴 합니다!  

> 엔티티에도 QuizType을 넣어서 분기처리 할 때 사용하면 깔끔해질 것 같네요

노을님께서 생각하신 방법과 비슷하게 리팩토링중입니다!

말씀하신 정적 팩토리도 그렇고 조금 더 좋은 방법을 고민중이예요

**Comment by 0sunset0** [comment]
리팩토링 대단하십니다...🫠
아 그리고 ci cd 해놨어요 하는 김에 도메인도요 
성공 실패 아마 잔디로 알림 올거에요

**Comment by wonslee** [comment]
오? 잔디 연동이 되는군요...! :rocket: 
부끄북극 리팩토링 계획 있으신가요?

**Comment by 0sunset0** [comment]
앗 지금 봤네요 ㅋㅋㅋ
잔디는 슬랙처럼 편하게는 안되고 직접 json을 보내면 되더라구요..?
리팩토링은,,, 테스트 코드 고치고 머 그롤 생각입니다ㅏ!!
cicd는 그냥 연습 삼아 해보고 싶기도 하고 하면 편하니까 했습니다..!

**Comment by 0sunset0** [comment]
원석님 잘 지내세요..? 이걸 보실지는 모르겠지만
제가 분기 처리에 대한 글을 읽다가 이 이슈가 생각나더라구요

Quiz에 선택지 리스트 필드가 필수적이지 않다면
Quiz에 multipleChoiceList를 보여주는 추상메서드를 선언하고, 하위 클래스에서 오버라이딩하면 
OCP를 위반하지 않을 것 같아요
이 방법이 어색하다면 OX와 객관식을 아예 다른 도메인으로 설계할 수도 있겠네요!

객체지향을 신경 쓰면서 부끄북극을 작업했던 것 같은데 지금 보니 부족한 게 많네요..ㅎㅎ
